<?php

namespace app\modules\admin\components;

use yii\filters\AccessControl;
use yii\web\Controller;

class BaseController extends Controller
{
    public $layout = 'admin';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ]; // TODO: Change the autogenerated stub
    }
}
