name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to the server
        uses: appleboy/ssh-action@master
        with:
          host: 157.245.27.189
          username: malik
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/prayforkg/site
            git checkout main && git pull && git checkout ${{ github.sha }}