name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: 157.245.27.189
          username: malik
          key: ${{ secrets.SSH_KEY }}
          source: "./*,!.git*"
          rm: true
          target: /home/prayforkg/site_static